version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - 5000:80
      - 5001:433
  db:
    image: postgres:13.4-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: lern
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
    volumes:
      - lern-db-postgresql:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:6.0
    ports:
      - 88:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@example.com
      - PGADMIN_DEFAULT_PASSWORD=test
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - lern-db-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  lern-db-postgresql:
    external: true
  lern-db-elasticsearch:
    external: true