version: '3.9'
services:
  backend:
    build: ./backend
    environment:
      - POSTGRES_STRING
      - CLOUDINARY_CLOUD
      - CLOUDINARY_APIKEY
      - CLOUDINARY_APISECRET
      - AZURE_SUBSCRIPTIONKEY
      - AZURE_ENDPOINT
  db:
    image: postgres:13.4-alpine
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - lern-db-postgresql:/var/lib/postgresql/data
volumes:
  lern-db-postgresql:
    external: true