version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - 5000:80
      - 5001:433
    envoirement:
      - POSTGRES_STRING
      - CLOUDINARY_CLOUD
      - CLOUDINARY_APIKEY
      - CLOUDINARY_APISECRET
      - AZURE_SUBSCRIPTIONKEY
      - AZURE_ENDPOINT
  db:
    image: postgres:13.4-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - lern-db-postgresql:/var/lib/postgresql/data
volumes:
  lern-db-postgresql:
    external: true