import * as Localization from "expo-localization";
import i18n from "i18n-js";

i18n.translations = {
  en: {
    login: {
      email: "Email",
      password: "Password",
      login: "Log in",
      registerNow: "Register now",
      registerDescription: "To register account, please fill the all fields",
      username: "Username",
      register: "Register",
      dashboard: "Dashboard",
      groups: "Groups",
      profile: "Profilr",
      yourSets: "Your sets",
      latestAdded: "Latest added",
      name: "Name",
      createGroup: "Create group",
      cancel: "Cancel",
      create: "Create",
      error: "Error",
      joinToGroup: "Join to group",
      code: "Code",
      join: "Join",
      sets: "Sets",
      profileSettings: "User settings",
      about: "About app",
      logout: "Log out",
      version: "Version",
      expoVersion: "Expo version",
      deviceName: "Device name",
      changeAvatar: "Change avatar",
      changePassword: "Change password",
      currentPassword: "Current password",
      repeatCurrentPassword: "Repeat current password",
      newPassword: "New password",
      otherOperations: "Other operations",
      deleteAccount: "Delete account",
      deleteAccountDescription:
        "Do you want delete account? This operation deletes your groups,\n" +
        "              sets and your personal information!",
      yesConfirm: "yes I'm confirm",
      createSet: "Create set",
      title: "Title",
      primaryLanguage: "Primary language",
      tags: "Tags",
      phrases: "Phrases",
      primaryPhrase: "Primary language",
      secondaryPhrase: "Secondary language (to translate)",
    },
  },
  pl: {
    email: "Email",
    password: "hasło",
    login: "Zaloguj",
    registerNow: "Zarejestruj teraz",
    registerDescription:
      "Aby zarejestrować konto, proszę wypełnić wszystkie pola",
    username: "Nazwa użytkownika",
    register: "Zarejestruj",
    dashboard: "Dashboard",
    groups: "Grupy",
    profile: "Profil",
    yourSets: "Twoje zestawy",
    latestAdded: "Ostatnio dodane",
    name: "Nazwa",
    createGroup: "Utwórz grupę",
    cancel: "Anuluj",
    create: "Utwórz",
    error: "Błąd",
    joinToGroup: "Dołącz do grupy",
    code: "Kod",
    join: "Dołącz",
    sets: "Zestawy",
    profileSettings: "Ustawienia użytkownika",
    about: "O aplikacji",
    logout: "Wyloguj się",
    version: "Wersja",
    expoVersion: "Wersja Expo",
    deviceName: "Nazwa urządzenia",
    changeAvatar: "Zmień avatar",
    changePassword: "Zmień hasło",
    currentPassword: "Aktualne hasło",
    repeatCurrentPassword: "Powtórz aktualne hasło",
    newPassword: "Nowe hasło",
    otherOperations: "Inne operacje",
    deleteAccount: "Usuń konto",
    deleteAccountDescription:
      "Czy ty chcesz usunąć hasło? Ta operacja usunie twoje wszystkie grupy, zestawy i dane personalne!",
    yesConfirm: "Tak, potwierdzam",
    createSet: "Utwórz zestaw",
    title: "Tytuł",
    primaryLanguage: "Jezyk podstawowy",
    tags: "Tagi",
    phrases: "Frazy",
    primaryPhrase: "Język podstawowy",
    secondaryPhrase: "Drugi jezyk (który ma zostać przetłumaczony)",
  },
};

i18n.locale = Localization.locale;
i18n.fallbacks = true;

export default i18n;
